#!/usr/bin/python -Es
from __future__ import print_function
import argparse
import functools
import os
import platform
import re
import sys
import textwrap

import configparser
import yaml

from toolsws.backends import Backend
from toolsws.backends import GridEngineBackend
from toolsws.backends import KubernetesBackend
from toolsws.tool import Tool
from toolsws.utils import wait_for
from toolsws.wstypes import WebService


BACKEND_DEFAULT = "kubernetes"
GRIDENGINE_DEFAULT_WSTYPE = "lighttpd"
KUBERNETES_DEFAULT_WSTYPE = "php7.3"

# Make all `print()` output go to stderr by default
print = functools.partial(print, file=sys.stderr)


def format_wstypes_block(config, default, leader="\n  * "):
    """Pretty print a list of runtime wstypes for a backend."""
    wstypes = []
    for name, spec in config.items():
        extra = ""
        if name == default:
            extra = " (default)"
        elif spec.get("deprecated", False):
            extra = " (DEPRECATED)"
        wstypes.append("{}{}".format(name, extra))
    return leader.join(sorted(wstypes))


def kube_quant(string):
    """
    A type for args that roughly matches up with Kubernetes' quantity.go
    General form is <number><suffix>
    The following are acceptable suffixes

    base1024: Ki | Mi | Gi | Ti | Pi | Ei
    base1000: n | u | m | "" | k | M | G | T | P | E
    """
    valid_suffixes = [
        "Ki",
        "Mi",
        "Gi",
        "Ti",
        "Pi",
        "Ei",
        "n",
        "u",
        "m",
        "",
        "k",
        "M",
        "G",
        "T",
        "P",
        "E",
    ]
    pattern = re.compile(r"^(\d+)([A-Za-z]{0,2})$")
    quant_check = pattern.match(string)
    if quant_check:
        suffix = quant_check.group(2)
        if suffix in valid_suffixes:
            return string

    msg = "{} is not a valid Kubernetes quantity".format(string)
    raise argparse.ArgumentTypeError(msg)


def start(job, message):
    try:
        job.request_start()
    except WebService.InvalidWebServiceException as e:
        raise SystemExit(e.message)
    # FIXME: Treat pending state differently.
    return wait_for(lambda: job.get_state() == Backend.STATE_RUNNING, message)


def stop(job, message):
    job.request_stop()
    return wait_for(lambda: job.get_state() == Backend.STATE_STOPPED, message)


def update_manifest(job, action, args):
    """
    Update a tool's service manifest to indicate the type of webservice in use

    :param action 'start' or 'stop'
    :param args parsed cli arguments
    """
    if action == "start":
        if (
            "web" not in job.tool.manifest
            or job.tool.manifest["web"] != job.wstype
        ):
            job.tool.manifest["distribution"] = platform.linux_distribution()[
                0
            ]
            job.tool.manifest["web"] = job.wstype
            if args.canonical:
                job.tool.manifest["canonical"] = args.canonical
            if args.replicas != 1:
                job.tool.manifest["replicas"] = args.replicas
            if hasattr(job, "container_resources"):
                # Not using the value directly to avoid persisting values from
                # the old Kubernetes cluster
                if args.cpu is not None:
                    job.tool.manifest["cpu"] = args.cpu
                if args.memory is not None:
                    job.tool.manifest["memory"] = args.memory
            if job.extra_args:
                job.tool.manifest["web::extra_args"] = job.extra_args

            job.tool.save_manifest()
    elif action == "stop":
        if "web" in job.tool.manifest:
            for key in [
                "distribution",
                "web",
                "backend",
                "canonical",
                "cpu",
                "memory",
                "replicas",
                "web::extra_args",
            ]:
                if key in job.tool.manifest:
                    del job.tool.manifest[key]
            job.tool.save_manifest()
    else:
        # blow up!
        raise Exception("action has to be 'start' or 'stop', got %s" % action)


if __name__ == "__main__":
    description = """
    Online documentation: https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web

    Supported webservice types:
      Kubernetes backend:
        * {kubernetes}
      Grid Engine backend:
        * {gridengine}
    """.format(
        kubernetes=format_wstypes_block(
            KubernetesBackend.CONFIG,
            KUBERNETES_DEFAULT_WSTYPE,
            leader="\n        * ",
        ),
        gridengine=format_wstypes_block(
            GridEngineBackend.CONFIG,
            GRIDENGINE_DEFAULT_WSTYPE,
            leader="\n        * ",
        ),
    )

    # The bootstrap parser is used to look for a --template=... arg. If one is
    # found, or if the default $HOME/service.template file exists, then it is
    # loaded as a YAML file and used to inject defaults into the main argument
    # parser.
    bootstrap = argparse.ArgumentParser(add_help=False)
    bootstrap.add_argument(
        "--template",
        dest="template_file",
        type=argparse.FileType(mode="r"),
        help="service.template to use when starting a webservice",
    )

    argparser = argparse.ArgumentParser(
        description=textwrap.dedent(description),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        parents=[bootstrap],
    )
    argparser.add_argument(
        "--backend",
        choices=["gridengine", "kubernetes"],
        help="Which cluster backend to use run the webservice",
    )
    argparser.add_argument(
        "--canonical",
        action="store_true",
        help="Redirect legacy URL to the canonical $TOOL.toolforge.org URL",
    )
    argparser.add_argument(
        "wstype",
        nargs="?",
        metavar="TYPE",
        help="Type of webservice to start",
    )

    allowed_actions = ["start", "stop", "status", "restart", "shell"]
    argparser.add_argument(
        "action",
        choices=allowed_actions,
        metavar="ACTION",
        help="Action to perform: {}".format(", ".join(allowed_actions)),
    )
    argparser.add_argument(
        "extra_args",
        nargs="*",
        metavar="...",
        help="Extra arguments to be parsed by the chosen TYPE",
    )
    # Backwards compat with older webservice.
    # Allows for webservice --release trusty lighttpd <action>
    argparser.add_argument(
        "--release", help=argparse.SUPPRESS, choices=["trusty"]
    )

    k8s_group = argparser.add_argument_group("Kubernetes backend options")
    k8s_group.add_argument(
        "-m",
        "--mem",
        required=False,
        type=kube_quant,
        help="Set higher Kubernetes memory limit",
        dest="memory",
    )
    k8s_group.add_argument(
        "-c",
        "--cpu",
        required=False,
        type=kube_quant,
        help="Set a higher Kubernetes cpu limit",
        dest="cpu",
    )
    k8s_group.add_argument(
        "-r",
        "--replicas",
        required=False,
        type=int,
        default=1,
        help="Set the number of pod replicas to use",
    )

    template_extra_args = None
    # Use the bootstrap argparser to check for a --template=... arg
    bootstrap_args, remainder_argv = bootstrap.parse_known_args()
    default_template = os.path.expanduser("~/service.template")
    if not bootstrap_args.template_file and os.path.exists(default_template):
        bootstrap_args.template_file = open(default_template, mode="r")
    if bootstrap_args.template_file:
        # Load settings from the template file and validate them by running
        # them through argparser as though they had been passed in the command
        # line.
        tmpl = yaml.safe_load(bootstrap_args.template_file)
        tmpl_argv = []
        if "backend" in tmpl:
            tmpl_argv.append("--backend={}".format(tmpl["backend"]))
        if "canonical" in tmpl and tmpl["canonical"]:
            tmpl_argv.append("--canonical")
        if "cpu" in tmpl:
            tmpl_argv.append("--cpu={}".format(tmpl["cpu"]))
        if "mem" in tmpl:
            tmpl_argv.append("--mem={}".format(tmpl["mem"]))
        if "replicas" in tmpl:
            tmpl_argv.append("--replicas={}".format(tmpl["replicas"]))
        if "type" in tmpl:
            tmpl_argv.append(tmpl["type"])

        tmpl_argv.append("start")  # always parse template as a 'start' action

        if "extra_args" in tmpl:
            tmpl_argv.append("--")
            tmpl_argv.extend(tmpl["extra_args"])

        class ThrowingArgumentParser(argparse.ArgumentParser):
            """ArgumentParser subclass that throws errors rather than exiting.

            From https://stackoverflow.com/a/14728477/8171
            """

            def error(self, message):
                raise ValueError(message)

        parser = ThrowingArgumentParser(add_help=False, parents=[argparser])
        try:
            template_args = parser.parse_args(tmpl_argv)
            # If parse_args() passed, set the values as defaults for the real
            # argument parsing phase.
            argparser.set_defaults(
                backend=template_args.backend,
                canonical=template_args.canonical,
                cpu=template_args.cpu,
                memory=template_args.memory,
                replicas=template_args.replicas,
                wstype=template_args.wstype,
            )
            # The argument gathering behavior of extra args does not work as
            # a default on the parser. It also will cause problems if the
            # template is providing TYPE as ArgumentParser will get confused
            # about where the extra args start. This seems to be the case even
            # if using a "--" sentinal token in the argument list to indicate
            # that everything after that should be treated as a positional
            # argument. This is really a flaw in the CLI of this tool
            # (optional positional arguments), but fixing that now is
            # a potentially large communications problem.
            template_extra_args = template_args.extra_args
        except ValueError as e:
            print(
                "Your template file ({}) contains errors:".format(
                    bootstrap_args.template_file.name
                )
            )
            print("  {}".format(str(e)))
            sys.exit(1)

    args = argparser.parse_args(args=remainder_argv)

    tool = Tool.from_currentuser()

    # We use this logic rather than setting defaults in argparse.
    # This allows us to default to spec in service.manifest but override
    # by specifying --backend option on the CLI
    rc_backend = None
    webservicerc = os.path.expanduser("~/.webservicerc")
    if os.path.exists(webservicerc):
        config = configparser.ConfigParser()
        config.read(webservicerc)
        try:
            rc_backend = config.get("Default", "--backend")
        except configparser.Error as e:
            print("Error reading {}: {}".format(webservicerc, e))

    # Select the first of:
    # * --backend=... from cli args
    # * 'backend' from service.manifest
    # * --backend=... from ~/.webservicerc
    backend = args.backend
    if backend is None:
        backend = tool.manifest.get("backend", rc_backend)

    if backend is None:
        print("WARNING: No explict backend provided.")
        print("  Using default of '{}'".format(BACKEND_DEFAULT))
        print(
            "  For help refer to <https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web>"
        )
        backend = BACKEND_DEFAULT

    if args.action != "shell":
        if "backend" in tool.manifest and tool.manifest["backend"] != backend:
            manifest_file = tool.get_homedir_subpath("service.manifest")
            print(
                "Backend '{}' from {} does not match '{}'".format(
                    tool.manifest["backend"], manifest_file, backend,
                )
            )
            print("  Try stopping your current webservice:")
            print("    webservice stop")
            print("  Then try starting it again:")
            print("    {}".format(" ".join(sys.argv)))
            print(
                "  If you have already tried that and it did not help, "
                "remove the state file before retrying:"
            )
            print("    rm {}".format(manifest_file))
            sys.exit(1)

    if backend == "gridengine":
        # Backwards compatibility hack to support
        # 'webservice --release trusty lighttpd start' invocations
        if args.release is not None:
            print("--release is deprecated and has no effect")
        if args.memory is not None:
            print("--mem is only for --backend=kubernetes")
            print("Please run again without this argument")
            sys.exit(1)
        if args.cpu is not None:
            print("--cpu is only for --backend=kubernetes")
            print("Please run again without this argument")
            sys.exit(1)
        if args.replicas != 1:
            print("--replicas is only for --backend=kubernetes")
            print("Please run again without this argument")
            sys.exit(1)
        if args.wstype is None:
            args.wstype = tool.manifest.get("web", GRIDENGINE_DEFAULT_WSTYPE)
        acceptable_wstypes = GridEngineBackend.CONFIG
    elif backend == "kubernetes":
        if args.release is not None:
            print("--release is not implemented for --backend=kubernetes")
            print("Please just pick an appropriate type instead")
            sys.exit(1)
        if args.wstype is None:
            args.wstype = tool.manifest.get("web", KUBERNETES_DEFAULT_WSTYPE)

        if args.cpu is None:
            args.cpu = tool.manifest.get("cpu", None)

        if args.memory is None:
            args.memory = tool.manifest.get("memory", None)

        if args.replicas == 1:
            args.replicas = tool.manifest.get("replicas", 1)

        acceptable_wstypes = KubernetesBackend.CONFIG

    if not args.canonical:
        args.canonical = tool.manifest.get("canonical", False)

    if not args.extra_args:
        args.extra_args = tool.manifest.get(
            "web::extra_args", template_extra_args
        )

    if args.wstype not in acceptable_wstypes.keys():
        print("type must be one of:")
        print(format_wstypes_block(acceptable_wstypes, ""))
        sys.exit(1)

    if backend == "gridengine":
        job = GridEngineBackend(
            tool,
            args.wstype,
            canonical=args.canonical,
            extra_args=args.extra_args,
        )
    else:
        job = KubernetesBackend(
            tool,
            args.wstype,
            canonical=args.canonical,
            mem=args.memory,
            cpu=args.cpu,
            replicas=args.replicas,
            extra_args=args.extra_args,
        )

    tool.manifest["backend"] = backend

    if job.is_deprecated(args.wstype):
        print("DEPRECATED: '{}' type is deprecated.".format(args.wstype))
        print(
            "  See https://wikitech.wikimedia.org/wiki/Help:Toolforge/{}".format(
                "Kubernetes" if backend == "kubernetes" else "Web"
            )
        )
        print("  for currently supported types.")

    if args.action == "start":
        if job.get_state() != Backend.STATE_STOPPED:
            print("Your job is already running")
            sys.exit(1)

        start(job, "Starting webservice")
        update_manifest(job, "start", args)

    elif args.action == "stop":
        if job.get_state() == Backend.STATE_STOPPED:
            print("Your webservice is not running", file=sys.stdout)
        else:
            stop(job, "Stopping webservice")
        update_manifest(job, "stop", args)

    elif args.action == "restart":
        if job.get_state() != Backend.STATE_RUNNING:
            start(job, "Your job is not running, starting")
            update_manifest(job, "start", args)
        else:
            job.request_restart()
        tool.save_manifest()

    elif args.action == "status":
        if job.get_state() != Backend.STATE_STOPPED:
            print(
                "Your webservice of type {} is running on backend {}".format(
                    job.wstype, backend
                ),
                file=sys.stdout,
            )
        else:
            print("Your webservice is not running", file=sys.stdout)

    elif args.action == "shell":
        if backend != "kubernetes":
            print("ERROR: shell is only supported for kubernetes backend")
            sys.exit(1)
        job.shell()
