#!/usr/bin/python
from __future__ import print_function
import argparse
import sys

from toollabs.webservice import WebServiceJob, WebService
from toollabs.webservice.services import webservice_classes
from toollabs.common.utils import wait_for
from toollabs.common import Tool


argparser = argparse.ArgumentParser()
argparser.add_argument('type', help='Type of webservice to start',
                       choices=webservice_classes.keys(), nargs='?')
argparser.add_argument('action', help='Action to perform',
                       choices=['start', 'stop', 'restart'])
argparser.add_argument('extra_args', help='Extra arguments to be parsed by the chosen webservicetype',
                       nargs='?')
# Backwards compat with older webservice. Allows for webservice --release precise lighttpd <action>
argparser.add_argument('--release',
                       help=argparse.SUPPRESS,
                       choices=['precise', 'trusty'])


def start(job, message):
    try:
        job.request_start()
    except WebService.InvalidWebServiceException as e:
        raise SystemExit(e.message)
    wait_for(lambda: job.is_running(), message)


def stop(job, message):
    job.request_stop()
    wait_for(lambda: not job.is_running(), message)


if __name__ == '__main__':
    args = argparser.parse_args()

    # Backwards compatibility hack to support 'webservice --release precise lighttpd start' invocations
    if args.release is not None:
        if args.type == 'lighttpd':
            if args.release == 'precise':
                args.type = 'lighttpd-precise'
                print("--release=precise is deprecated. Use %s lighttpd-precise <action> instead" % sys.argv[0])
            elif args.release == 'trusty':
                print("--release=trusty is deprecated. Use %s %s <action> instead " % sys.argv[0], args.type)
        else:
            print("--release is deprecated and has no effect, using trusty...")
            args.release = 'trusty'

    tool = Tool.from_currentuser()
    if args.type is None:
        args.type = tool.manifest.get('web', 'lighttpd')

    webservice = webservice_classes[args.type](tool, args.extra_args)

    job = WebServiceJob(webservice)

    if args.action == 'start':
        if job.is_running():
            print('Your job is already running')
            sys.exit()

        start(job, 'Starting webservice')
        webservice.update_manifest('start')

    elif args.action == 'stop':
        if not job.is_running():
            print('Your webservice is not running')
            sys.exit()

        stop(job, 'Stopping webservice')
        webservice.update_manifest('stop')

    elif args.action == 'restart':
        if not job.is_running():
            start(job, 'Your job is not running, starting')
        else:
            stop(job, 'Restarting webservice')
            start(job, '')

    print()  # End program with newline, don't output newline anywhere else :)
