#!/usr/bin/python -Es
import argparse

from toolsws.tool import Tool
from toolsws import proxy
from toolsws.wstypes import WSTYPES

argparser = argparse.ArgumentParser()
argparser.add_argument(
    "--type",
    dest="wstype",
    help="Type of webservice to start",
    choices=WSTYPES.keys(),
)
argparser.add_argument(
    "--port", help="Port to bind the webservice to", type=int, default=0
)
argparser.add_argument(
    "--register-proxy",
    action="store_true",
    help="Register webservice with proxy",
)
argparser.add_argument(
    "extra_args",
    nargs=argparse.REMAINDER,
    help="Extra arguments optionally passed to the chosen webservice type",
)
argparser.add_argument(
    "--canonical", action="store_true", help=argparse.SUPPRESS,
)
args = argparser.parse_args()


tool = Tool.from_currentuser()
if args.port != 0:
    port = args.port
else:
    port = proxy.get_open_port()

webservice = WSTYPES[args.wstype](tool, args.extra_args)

if args.register_proxy:
    proxy.register(port)
webservice.run(port)
