#!/usr/bin/python
import argparse

from toollabs.common import Tool
from toollabs.webservice import proxy
from toollabs.webservice.services import webservice_classes

argparser = argparse.ArgumentParser()
argparser.add_argument('--type', help='Type of webservice to start',
                       choices=webservice_classes.keys())
argparser.add_argument('--extra_args', help='Extra arguments optionally passed to the chosen webservice type')
args = argparser.parse_args()


tool = Tool.from_currentuser()
port = proxy.get_open_port()

webservice = webservice_classes[args.type](tool, args.extra_args)

proxy.register(port)
webservice.run(port)
